# Numpy Array Programming

## 1차원 배열 만들기 

In [1]:
import numpy as np

ar = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
type(ar)

numpy.ndarray

## 벡터화 연산

In [3]:
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

answer=[]
for di in data:
    answer.append(2*di)
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [4]:
x = np.array(data)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
x* 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

2 * a + b

array([12, 24, 36])

# 2차원 배열 만들기

In [7]:
c = np.array([[0,1,2], [3,4,5]])
c

array([[0, 1, 2],
       [3, 4, 5]])

# 3차원 배열 만들기

In [8]:
d = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[11, 12, 13, 14],
               [15, 16, 17, 18],
               [19, 20, 21, 22]]])   # 2 x 3 x 4 array
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

# 배열의 차원과 크기 알아내기

In [9]:
a = np.array([1, 2, 3])

print(a.ndim) # 배열의 차원
print(a.shape) # 배열의 크기를 반환

1
(3,)


In [10]:
# c = np.array([[0,1,2], [3,4,5]])
print(c.ndim)
print(c.shape)

2
(2, 3)


In [11]:
print(d.ndim)
print(d.shape)

3
(2, 3, 4)


# 배열의 인덱싱

In [12]:
a = np.array([0,1,2,3,4])
a[2]

2

In [13]:
a[-1]

4